GET http://localhost:3000/characters/
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMDM5MzcwZjkxYWU2MzY2Y2QwNjcwNyIsImVtYWlsIjoiYm9jYWoueG1sQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDctMDZUMjE6MTE6MTIuNDY4WiIsImlhdCI6MTU5NDA3Mjg4OX0.f5z9qAHkEe3TFlXz0rsnTXpjDDGr2b5c9pdnbnu4gOk

###
GET http://localhost:3000/characters/5f03d101d33cf00d2c52949a
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMDM5MzcwZjkxYWU2MzY2Y2QwNjcwNyIsImVtYWlsIjoiYm9jYWoueG1sQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDctMDZUMjE6MTE6MTIuNDY4WiIsImlhdCI6MTU5NDA3Mjg4OX0.f5z9qAHkEe3TFlXz0rsnTXpjDDGr2b5c9pdnbnu4gOk

###
POST http://localhost:3000/characters
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMDM5MzcwZjkxYWU2MzY2Y2QwNjcwNyIsImVtYWlsIjoiYm9jYWoueG1sQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjAtMDctMDZUMjE6MTE6MTIuNDY4WiIsImlhdCI6MTU5NDA3Mjg4OX0.f5z9qAHkEe3TFlXz0rsnTXpjDDGr2b5c9pdnbnu4gOk
Content-Type: application/json

{
  "owner": "5f039370f91ae6366cd06707",
  "name": "Tommy",
  "heritage": "Human",
  "traits": [
    "Stubborn",
    "Strong",
    "Fast",
    "Tough"
  ],
  "proficiency": "Light",
  "mastery": "Clubs"
}

###
PATCH http://localhost:3000/characters/5efccf888488c72ce42090a1
Content-Type: application/json

{
  "name": "Timmy"
}

###
DELETE http://localhost:3000/characters/5f03cc2520e0651610aade1e
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlZmQwMzdjNDMxY2IzMDVlMDFlMzc3ZiIsImVtYWlsIjoidG9ueUBzdGFyay5uZXQiLCJjcmVhdGVkQXQiOiIyMDIwLTA3LTAxVDIxOjQzOjI0LjkyN1oiLCJpYXQiOjE1OTM3Mjg0Mzd9.PqlJFfhU4eFkMOc3HhqcnJwXiltzpKDXXCQZYX8tADQ